//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomationDashboardMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AutomationDBEntities : DbContext
    {
        public AutomationDBEntities()
            : base("name=AutomationDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AutomationTask> AutomationTasks { get; set; }
        public virtual DbSet<ManagerJob> ManagerJobs { get; set; }
        public virtual DbSet<SlaveMachine> SlaveMachines { get; set; }
        public virtual DbSet<ActiveAutomationBuild> ActiveAutomationBuilds { get; set; }
    }
}
