//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomationDashboardMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutomationTask
    {
        public int Id { get; set; }
        public byte[] Config { get; set; }
        public byte[] AutomationReport { get; set; }
        public Nullable<bool> IsComplete { get; set; }
        public string SlaveId { get; set; }
        public Nullable<int> JobId { get; set; }
        public string Suite { get; set; }
        public string SuiteName { get; set; }
        public string TimeForCompletion { get; set; }
        public byte[] DBExceptionsLog { get; set; }
        public byte[] ConfigurationsUsedForExecution { get; set; }
    
        public virtual ManagerJob ManagerJob { get; set; }
        public virtual SlaveMachine SlaveMachine { get; set; }
    }
}
