//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomationDashboardMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailySmoke
    {
        public int id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public byte[] detail_results { get; set; }
        public string test_run_stats { get; set; }
        public Nullable<int> TeamId { get; set; }
    
        public virtual ProductTeam ProductTeam { get; set; }
    }
}
