//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomationDashboardMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManagerJob
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ManagerJob()
        {
            this.AutomationTasks = new HashSet<AutomationTask>();
        }
    
        public int Id { get; set; }
        public string AutomationRunType { get; set; }
        public Nullable<bool> Status { get; set; }
        public byte[] Config { get; set; }
        public string TimeForCompletion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutomationTask> AutomationTasks { get; set; }
        public virtual ActiveAutomationBuild ActiveAutomationBuild { get; set; }
    }
}
