//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomationDashboardMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTeam
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductTeam()
        {
            this.AutomateDatas = new HashSet<AutomateData>();
            this.CoreModSmokes = new HashSet<CoreModSmoke>();
            this.DailySmokes = new HashSet<DailySmoke>();
            this.FullPasses = new HashSet<FullPass>();
            this.WeeklyTriagings = new HashSet<WeeklyTriaging>();
            this.TestPlans = new HashSet<TestPlan>();
        }
    
        public int TeamId { get; set; }
        public string TeamName { get; set; }
        public string TeamProject { get; set; }
        public string TestPlanName { get; set; }
        public Nullable<int> TotalTFSTests { get; set; }
        public Nullable<int> TotalAutomatedTests { get; set; }
        public Nullable<int> TotalExpectedTests { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutomateData> AutomateDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoreModSmoke> CoreModSmokes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DailySmoke> DailySmokes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FullPass> FullPasses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WeeklyTriaging> WeeklyTriagings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestPlan> TestPlans { get; set; }
    }
}
