//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomationDashboardMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestPlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TestPlan()
        {
            this.TestSuites = new HashSet<TestSuite>();
        }
    
        public int PlanId { get; set; }
        public string TestPlanName { get; set; }
        public int TeamId { get; set; }
        public int TestCaseCount { get; set; }
    
        public virtual ProductTeam ProductTeam { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestSuite> TestSuites { get; set; }
    }
}
