//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomationDashboardMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeeklyTriaging
    {
        public int EntryNumber { get; set; }
        public Nullable<int> TeamId { get; set; }
        public string ProductArea { get; set; }
        public Nullable<int> NoOfTestCasesDebugged { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual ProductTeam ProductTeam { get; set; }
    }
}
